### ISSUE TITLE
version number?

### ISSUE THREAD

**Issue by gangelop** [AlessandroYorba/Alduin#1]
Hi Alessandro,

Thanks for sharing this theme. It's super neat! One question: Would you consider applying a version number? I'm asking because I want to make an archlinux package, and without a version number this can be tricky.

**Comment by AlessandroYorba** [comment]
Thank you sir! I just tagged it as Version 1.0 and noted release version in the file.

**Comment by AlessandroYorba** [comment]
Done! Version 1.0 of Alduin has a tagged release of version 1.0 on Git Hub.
Thank you. Glad you like it!!!!

**Comment by gangelop** [comment]
FYI, [simple archlinux package](https://aur.archlinux.org/packages/vim-colorscheme-alduin)

**Comment by AlessandroYorba** [comment]
I'm honored!! Thank you
