### ISSUE TITLE
SignColumn

### ISSUE THREAD

**Issue by ghost** [AlessandroYorba/Alduin#10]
Looks a bit striking against the suggested CursorLine colour, and a bit too bright for the theme as a whole, I think:

![screenshot_2016-02-19_11-52-37](https://cloud.githubusercontent.com/assets/198665/13174991/493cb656-d6ff-11e5-9305-5eb714e346c4.png)

How about making it the same colour, with `SignColumn ctermfg=14 ctermbg=235 guifg=Cyan guibg=#262626`:

![screenshot_2016-02-19_11-53-33](https://cloud.githubusercontent.com/assets/198665/13175017/6d53e410-d6ff-11e5-9cb8-7e042ed2cc10.png)

**Comment by AlessandroYorba** [comment]
I like the idea that the SignColumn match the LineNr and FoldColumn groups. Remember that your LineNr is based on a custom setting. You definitely bring up something to consider. Thank you for the observation.

**Comment by AlessandroYorba** [comment]
@NightVigil SignColumn has been updated in the latest commit. I took your advise and I added the green foreground color that you were using. However, I left the background dark to match the LineNr highlight group for either the default alduin or Ethereal. Thanks
