### ISSUE TITLE
Text in quotations '  '  or "  "  are highlighted

### ISSUE THREAD

**Issue by esn89** [AlessandroYorba/Alduin#11]
Right now, I don't know if this is a feature.   I have a feeling it isn't.  My code right now looks like this:

https://i.imgur.com/vLF2kLZ.png

As you can see, there is a bit of highlighting going on, on the words 'ycmd' and 'third_party'.

Any ideas as to why, or how to get rid of this?

**Comment by gangelop** [comment]
I have a feeling this _is_ a feature. At least, I like it. :smile:

**Comment by AlessandroYorba** [comment]
@esn89 Thanks. Yes, that is a feature. At one point, I considered making a Shout called Clear Skies that would toggled the String background color on and off. I'll consider adding that feature if more people request it. In the meantime, the best way to remove the background highlight is a work around. Open your copy  `.vim/colors/alduin.vim` and add this snippet to the very bottom of the file

``` VimL
" Removes String Background Color:
highlight String ctermbg=none guibg=none
```

Just remember that if you ever update or clone alduin again you'll have to add it back in. Please let me know if the code I gave you works out. I'll leave this ticket open so others can share their thoughts.

**Comment by esn89** [comment]
@AlessandroYorba thank you for your help. That works like a charm and I love it.

**Comment by AlessandroYorba** [comment]
@esn89 great Thank you for your input, I will in fact work on a setting to toggle that option on and off. I'll repost here to notify you.

**Comment by esn89** [comment]
@AlessandroYorba 

You're welcome.  I really appreciate you taking your time to work on this minor issue.

Thanks!

**Comment by AlessandroYorba** [comment]
@esn89 better late than never?
In the latest commit you can now disable the background highlight for Strings.
`let g:alduin_Shout_Animal_Allegiance = 1`
`colo alduin`

**Comment by gangelop** [comment]
Noooooooo! 9e6fe2f
Did you remove the string highlighting completely?
I liked this.
At least change the default and leave it optional. =)

**Comment by AlessandroYorba** [comment]
@lathan String bk highlight have returned.

**Comment by AlessandroYorba** [comment]
@lathan hey see #15
