### ISSUE TITLE
Make internal colours accesible

### ISSUE THREAD

**Issue by SevereOverfl0w** [AlessandroYorba/Alduin#12]
Sometimes I want to reuse the colours from the alduin theme in my vim config, it would be really neat (if possible), so be able to access `alduin.colors` as a variable of some kind. That way I could define custom highlight groups & such, by reusing the colours defined there.

**Comment by AlessandroYorba** [comment]
Can you give me an example of what you are looking for? Thanks @SevereOverfl0w

**Comment by SevereOverfl0w** [comment]
I had to add this to customize the theme:

``` vim
hi StatusLine ctermbg=585858
```

It'd be nice to be able to do 

``` vim
hi StatusLine ctermbg=alduin.Nightingale
```

**Comment by AlessandroYorba** [comment]
Ah... I see. There just might be a way to do this!  I just read a post on stackoverflow where someone wanted to do something similar. See post: http://stackoverflow.com/questions/2211477/how-can-i-use-variables-to-dry-up-vim-colorthemes
It appears that the way to accomplish this is by writing an `execute:` command within the colorscheme. I created Alduin using the `call` command in the colorscheme, however your request sounds awesome. Let me play around with the exe in alduin and I'll see what I can come up with. Thanks @SevereOverfl0w
