### ISSUE TITLE
Neovim truecolor support

### ISSUE THREAD

**Issue by SevereOverfl0w** [AlessandroYorba/Alduin#13]
It would be really cool to support "truecolor" for terminals, this is a neovim feature for 16-million color selection. This has been done for solarized:

https://github.com/frankier/neovim-colors-solarized-truecolor-only

**Comment by AlessandroYorba** [comment]
Not a bad idea. It might solve a couple color issues that have been driving me crazy. For instance, iTerm renders term colors differently then it's matching gui counterpart. The "Trucolor", method  in theory should solve this problem by forcing the terminal to render hex values. I do not use NeoVim but I'll look into supporting it. Thank you for the tip @SevereOverfl0w

**Comment by AlessandroYorba** [comment]
@SevereOverfl0w Yo! Vim8 is rumored to have 24bit color support much like NeoVim. I plan on supporting both of them. And in light of having access to more than 256 colors, I'm now taking an even closer look at the current color palette as well as any additional colors that can be introduced. I'll keep you posted. I'll add a color chart to the repo markdown soon
