### ISSUE TITLE
SpellBad is hard on the eyes in terminal

### ISSUE THREAD

**Issue by gpakosz** [AlessandroYorba/Alduin#14]
Is there something broken on my side or is the `SpellBad` highlight group hard on the eyes?

![image](https://cloud.githubusercontent.com/assets/553208/17786514/6c87ee04-6585-11e6-81fc-848e962a52f9.png)

![image](https://cloud.githubusercontent.com/assets/553208/17786524/7c82b4c4-6585-11e6-83c7-5861dc36aa6b.png)

**Comment by AlessandroYorba** [comment]
You're absolutely right. It makes my eyes sweat! Truth be told, I wasn't sure what values to use for any of the Spelling HL groups. What you're seeing is a clash of my theme color `Windhelm` and Vim referencing the terminal theme colors. 

Are there any other vim color schemes that you'd like me to look at that got `SpellBad` right? Or do you have any suggestions on how it should look? Thanks for the feedback.

**Comment by gpakosz** [comment]
I don't know really :) Maybe make it close to the GUI look? That is red underline (even though in GUI it's a curvy underline)

![image](https://cloud.githubusercontent.com/assets/553208/17802274/8f8eef64-65ef-11e6-846a-676fbd63384f.png)

**Comment by AlessandroYorba** [comment]
@gpakosz try the latest commit. I added 4 new colors for the Spelling HL groups. I tried my best to add colors that are visible and that stand out from the other theme colors. Give it a shot and let me know if they help you out.

**Comment by gpakosz** [comment]
👍 looks good to me! Thanks

**Comment by AlessandroYorba** [comment]
Awesome! Thank you

**Comment by gangelop** [comment]
Awesome.
Time for release 2.4.5 maybe?
![spell](https://cloud.githubusercontent.com/assets/1893345/17966550/775b3e20-6ac2-11e6-94f3-6a472eb28907.jpg)

**Comment by AlessandroYorba** [comment]
@lathan good call. Working on that today.

**Comment by AlessandroYorba** [comment]
@lathan version 3 is tagged

**Comment by gangelop** [comment]
ty @AlessandroYorba !
