### ISSUE TITLE
Testing needed for termguicolor setting

### ISSUE THREAD

**Issue by AlessandroYorba** [AlessandroYorba/Alduin#15]
I need help from any Alduin users who willing / brave enough to test out a new color setting before it's announced as stable in the next version.  As you can see from the screenshot, it's a dark brown UI, with the standard Alduin color palette.  The catch is that it's Alduins first use of the new gui colors for terminals. Here are the requirements in order to enable this setting:

Requirements for Teminal Users:
1. Any terminal that supports 24 bit color. [list of 24 bit terminals](https://gist.github.com/XVilka/8346728)
2. Vim >= 7.4.1799 

Requirements for Teminal Users:
1. Tmux >= 2.2  [TrueColor in Tmux](http://homeonrails.com/2016/05/truecolor-in-gnome-terminal-tmux-and-neovim/)

in your vimrc

``` VimL
set termguicolors
let g:alduin_Shout_Summon_Odahviing = 1
colo alduin
```

***Note to any Vim User who is having an issue getting the gui colors to display in the terminal using the settings above. Please check out the vim help on the subject. I found that some users will need to input additional settings in the .vimrc

```
set t_8f=^[[38;2;%lu;%lu;%lum
set t_8b=^[[48;2;%lu;%lu;%lum
```

The "^[" is a single character. You enter it in INSERT mode by pressing CTRL+V and then ESC.

More help from Vim:
`:help xterm-true-color`

Requirements for Gui Users:
1. None ( should work out of box )

<img width="2025" alt="screen shot 2016-09-17 at 4 29 38 am" src="https://cloud.githubusercontent.com/assets/11221489/18607909/62f0fea0-7c8f-11e6-9b16-734ab350a3ff.png">

<img width="2025" alt="screen shot 2016-09-17 at 4 28 20 am" src="https://cloud.githubusercontent.com/assets/11221489/18607906/469e9500-7c8f-11e6-8068-817f03641d11.png">

**Comment by AlessandroYorba** [comment]
Moving these features to new repo

**Comment by gangelop** [comment]
Works with 
- `neovim 0.1.5`
- `tmux 2.2`
- `gnome-terminal 3.20.2`

![2016-09-17-143813_1188x740_scrot](https://cloud.githubusercontent.com/assets/1893345/18608243/850b7f24-7ce4-11e6-9b7e-4fa496b3585b.png)

**Comment by AlessandroYorba** [comment]
Awesome! I'm glad you grabbed that commit. I'm going to design a new colorscheme around that. Thanks dude! New commits will omit the Odahviing option.
