### ISSUE TITLE
Set Dragon Aspect as the default color setting and remove Default Alduin??

### ISSUE THREAD

**Issue by AlessandroYorba** [AlessandroYorba/Alduin#16]
I've been bouncing back between Ethereal Mode and Dragon Aspect, and I haven't even touched the default Alduin since adding either of the theme options. I realize that colors are totally subjective but I can help wonder if Dragon Aspect is just superior.

Wondering if any of you have tried Dragon Aspect? 
Do you like it better than the default?
Should Dragon Aspect be the standard?

**Comment by gangelop** [comment]
Dragon Aspect looks good.

**Comment by AlessandroYorba** [comment]
@lathan try the latest commit. Default is darker and folds are darker. Let me know, and I'll edit the tag and version. Thanks dude

**Comment by gangelop** [comment]
I like it. :) ty :+1:
