### ISSUE TITLE
Vampirism setting has been deprecated

### ISSUE THREAD

**Issue by AlessandroYorba** [AlessandroYorba/Alduin#18]
Setting time based variables to change aspect of a colorscheme is something that should be a task for the .vimrc and not the responsibility for the colorscheme. Keeping it in the .vimrc also has the added benefit of creating other special conditions or settings that complement each users personal preference. I will add a gist or just update this issue with some legacy code for Vampirism so that you can add it to your .vimrc
:smiling_imp:

**Comment by AlessandroYorba** [comment]
false

**Comment by lgalke** [comment]
I liked the vampires. Did you put a gist somewhere? Guess I could also extract the code snippet from some earlier commit..

**Comment by AlessandroYorba** [comment]
@lgalke try adding this to your .vimrc. 

```VimL
    let hour = strftime("%H")

    " 7am - 5pm 
    if 7 <= hour && hour < 17
        let g:alduin_Shout_Dragon_Aspect = 0
        let g:alduin_Shout_Become_Ethereal = 0

    " 5pm - 12am
    elseif 17 <= hour && hour < 24
        let g:alduin_Shout_Dragon_Aspect = 1
        let g:alduin_Shout_Become_Ethereal = 0

    " 12am - 7am
    else
        let g:alduin_Shout_Dragon_Aspect = 0
        let g:alduin_Shout_Become_Ethereal = 1
    endif
```

**Comment by lgalke** [comment]
Thanks, that's great.
