### ISSUE TITLE
Remove screenshot files from repository

### ISSUE THREAD

**Issue by mcchrish** [AlessandroYorba/Alduin#2]
Image files are huge and they are carried around everytime someone wants to use your colorscheme. I think it's possible to upload the screenshots in a github issue and just use the URL generated once uploaded.

**Comment by AlessandroYorba** [comment]
Good point. I'll lighten the load immediately by removing most of the screenshot and then URL them

**Comment by conorsch** [comment]
OK, it's not bad to pare down the repository a bit, but you can always just:

```
wget https://raw.githubusercontent.com/AlessandroYorba/Alduin/master/colors/alduin.vim -O ~/.vim/colors/alduin.vim
```

and don't bother cloning the history.

**Comment by AlessandroYorba** [comment]
Thank you both for the ideas and feedback. I removed the Screenshot Dir from the repo and just referenced the images from within a Github issue.
