### ISSUE TITLE
vimrc settings for darker and lighter variants 

### ISSUE THREAD

**Issue by gilfra0000** [AlessandroYorba/Alduin#24]
hello,

There appears to be no change from the default UI when I add the settings for darker and lighter variants of alduin to my vimrc. I was able to change Highlight! Folded colors. 

Can't see what, if anything, I'm doing incorrectly.

![alduin_1](https://user-images.githubusercontent.com/15451744/32141982-b242e07c-bc85-11e7-8408-1f55625cb66c.PNG)

Help appreciated, Gilbert

**Comment by AlessandroYorba** [comment]
Launch vim again with those settings. 
From command mode read me the output for ```:highlight Normal``` <enter>

Here's what I show when my vimrc has:
```VimL
let g:alduin_Shout_Become_Ethereal = 1
colorscheme alduin 
```
![screen shot 2017-10-29 at 9 16 25 am](https://user-images.githubusercontent.com/11221489/32145680-f1d1fc9c-bc89-11e7-95c8-740e525fd9f7.png)
<br><br>

Here's what I show when this is set in my vimrc:
```VimL
colorscheme alduin 
```
![screen shot 2017-10-29 at 9 19 16 am](https://user-images.githubusercontent.com/11221489/32145696-4ddfa390-bc8a-11e7-8321-e1cffa93c108.png)

**Comment by AlessandroYorba** [comment]
@aetherpress Hey just following up I wanted to see if the Become Ethereal setting worked out okay.

**Comment by gilfra0000** [comment]
hello sorry for the delay. i got the same results as those in your screenshots. thanks for your help and the great color scheme.

**Comment by AlessandroYorba** [comment]
cool
