### ISSUE TITLE
CursorColumn's color seems too light

### ISSUE THREAD

**Issue by einenlum** [AlessandroYorba/Alduin#25]
Hi there. Thanks for the colorscheme, it's beautiful!

Just a thing that bothers me: the CursorColumn color is very light and it's a bit disharmonious.

![selection_013](https://user-images.githubusercontent.com/5675200/42133076-e20aad1c-7d23-11e8-95c3-639e714afaa3.png)

Wouldn't it be better and more logical to set the CursorColumn's color the same as the CursorLine's color?

![selection_014](https://user-images.githubusercontent.com/5675200/42133082-0f7677ae-7d24-11e8-91b5-ab364522fb7f.png)

**Comment by AlessandroYorba** [comment]
@Einenlum I like your idea of matching the cursorcolumn with the cursorline. Try the dev version here: https://github.com/AlessandroYorba/Alduin/tree/nightly

**Comment by einenlum** [comment]
@AlessandroYorba Thanks for your reactivity! It's great, I love this new version :).
