### ISSUE TITLE
Bracket colour

### ISSUE THREAD

**Issue by ghost** [AlessandroYorba/Alduin#4]
Love this theme, but there's just one thing..!

With my block cursor on the opening parenthesis, it actually looks like it's on the closing one:

![focused](https://cloud.githubusercontent.com/assets/198665/12715053/00ee93de-c8d0-11e5-8610-0f2dcf0e6551.png)

A funny this is, when that Vim window isn't focused, ie. I'm doing something in another window, it looks like this:

![unfocused](https://cloud.githubusercontent.com/assets/198665/12715077/23a0f412-c8d0-11e5-8ac1-2dceb1134aa9.png)

**Comment by gangelop** [comment]
Is that terminator? In my gnome-terminal I have the cursor blinking so then it is discernible, but still not obvious. I find myself always mistaking the cursor position.

My suggestion is a darker color for the "second" cursor.

**Comment by ghost** [comment]
It is Terminator!

**Comment by AlessandroYorba** [comment]
@NightVigil, I'm not sure why the first parens isn't showing up, especially when you're in that active window. Were you able to solve the issue in Terminator?

**Comment by AlessandroYorba** [comment]
@Lathan @NightVigil you guys both bring up an interesting point about the second paren. I just push a new commit that changes how MatchParens works. I can see that it was difficult to discern the cursor location when editing files that do not have highlighting for paren operators, e.g. Python or C++ or many others. See if the new commit works better for you guys. Thanks for the feedback.

**Comment by AlessandroYorba** [comment]
old behavior with vertical bar cursor
![matchparen](https://cloud.githubusercontent.com/assets/11221489/12731335/4db010fc-c8e5-11e5-9ee6-615bff43f9df.png)

New behavior with terminal vertical bar cursor
![matchparennew](https://cloud.githubusercontent.com/assets/11221489/12731284/10ce0ad6-c8e5-11e5-81b1-6d48b27a67be.png)

New behavior with terminal block cursor
![blockcursor](https://cloud.githubusercontent.com/assets/11221489/12732751/d0e6bb3c-c8eb-11e5-82d0-8a3b114593e6.png)

**Comment by ghost** [comment]
I'm not seeing a difference with a block cursor. I'll debug it later, it might be another plugin interfering.

**Comment by gangelop** [comment]
What I think needs to be done is to remove the bg color for the matching parenthesis and instead use underlining. This is what sublime text does by default. This is also done by [termschool](https://github.com/marcopaganini/termschool-vim-theme). At least this is what I would want and I think is an overall sane approach. I just have no idea how to write it in VimL.

**Comment by AlessandroYorba** [comment]
I just added an new feature that we can try out. We can debate the color used but at least the underline option can be applied. Get the latest commit of alduin then add this to your vimrc:

```
  "Changes MatchParen to underline
  let g:alduin_Shout_AuraWhisper = 1
  colo alduin
```

![underline](https://cloud.githubusercontent.com/assets/11221489/12767720/ae75fbe2-c9bf-11e5-90cc-d2ce25741990.png)

**Comment by gangelop** [comment]
:heart::heart::heart::heart::heart::heart:

**Comment by AlessandroYorba** [comment]
Cool! I'll keep this ticket open incase someone else has any input.

**Comment by ghost** [comment]
The ":set number" numbers are slightly too dark :-)

**Comment by AlessandroYorba** [comment]
Is it too dark for the default alduin mode or for `let g:alduin_Shout_Become_Ethereal = 1`  mode ? Or both?

**Comment by ghost** [comment]
Both. It might work better if it was the same as in the [distinguished](https://github.com/Lokaltog/vim-distinguished) colour scheme...

**Comment by AlessandroYorba** [comment]
I created a new Issue for the LineNr topic. I also have some screenshots for you to look at:  https://github.com/AlessandroYorba/Alduin/issues/6

**Comment by AlessandroYorba** [comment]
@lathan @NightVigil 
heads up! I will be making a very slight modification to the AruraWhisper Shout in alduin. If you use it with the next commit you'll have to change your vimrc to 

 `let g:alduin_Shout_Aura_Whisper = 1`  

Very minor I know but the spelling has been bugging me. Thanks again both of you for the feature suggestion

**Comment by gangelop** [comment]
@AlessandroYorba done[,](https://github.com/lathan/dotfiles/commit/ef20641a1b98e3a3ed5f4721109bfda67ec35bcd) thnx :)

**Comment by makkoncept** [comment]
I have been struggling for some time with this...
Thanks for making this change :)
Maybe you can add this (and all the other) global config variable(s) in the readme so that they can be found easily?

**Comment by AlessandroYorba** [comment]
@makkoncept good idea. I'll update the README and I'll add some comments in the colorscheme file.
