### ISSUE TITLE
LineNr highlight group

### ISSUE THREAD

**Issue by AlessandroYorba** [AlessandroYorba/Alduin#6]

**Comment by AlessandroYorba** [comment]
iTerm 2 Screenshot:
Default `LineNr  ctermfg=237 ctermbg=233 guifg=#3a3a3a guibg=#121212`
![linenr_default](https://cloud.githubusercontent.com/assets/11221489/13126359/f36eb55c-d57e-11e5-9927-d1a822d2bf6d.png)

**Comment by AlessandroYorba** [comment]
iTerm 2 Screenshot:
Ethereal Mode `LineNr  ctermfg=236 ctermbg=16 guifg=#303030 guibg=#000000`
![linenr_ethereal](https://cloud.githubusercontent.com/assets/11221489/13126366/fefceca4-d57e-11e5-99eb-bd291068e1a8.png)

The foreground color for the LineNr when in Ethereal mode is in fact darker the LineNr for Alduin default. To me the default setting is legible but the Ethereal Mode is too dark

**Comment by ghost** [comment]
How about `LineNr ctermfg=243 ctermbg=235 guifg=#767676 guibg=#262626` and for "81" in this screenshot, the same colour as the comment on the same line (I'm not sure how to set that):

![screenshot_2016-02-17_22-23-09](https://cloud.githubusercontent.com/assets/198665/13127047/3dd6d192-d5c5-11e5-8d5c-c89daef6df8b.png)

**Comment by AlessandroYorba** [comment]
Let me plug in your values to see how they look on my end.

**Comment by AlessandroYorba** [comment]
Here's the values you provided so I can compare your screenshot with mine:
Ethereal Mode:
`LineNr ctermfg=243 ctermbg=235 guifg=#303030 guibg=#000000`
![linenroption](https://cloud.githubusercontent.com/assets/11221489/13127454/4f258902-d584-11e5-9aac-84becfc7afc2.png)

**Comment by AlessandroYorba** [comment]
While I spend some time considering your request, here's a small snippet you can add to the very bottom of your alduin.vim. It should display the lineNr and CursorLineNr that you want in both the default alduin and Ethereal mode: 

```
"Lighter Line Number Settings
hi LineNr ctermfg=243 ctermbg=235

"Winterhold CursorLine Number Color
hi CursorLineNR ctermfg=101
```

Please note that if you update alduin to any new commits, you have to add the snippet back in. Also, are you using Terminator?

**Comment by ghost** [comment]
Here's what works for me.

Terminator:
![screenshot_2016-02-18_09-46-02](https://cloud.githubusercontent.com/assets/198665/13139422/7433b48a-d624-11e5-9614-1307688b048b.png)

GUI:
![screenshot_2016-02-18_09-46-53](https://cloud.githubusercontent.com/assets/198665/13139453/91e8eff4-d624-11e5-9bae-c67bd249006c.png)

As you can see, I had some difficulty trying to get the GUI's background colour the same as the cterm's. I actually prefer the GUI's. This is with g:alduin_Shout_Become_Ethereal set.

I have some other alterations that I'd like to suggest. Shall I make separate issues for them?

**Comment by AlessandroYorba** [comment]
I apologize. I gave you just the terminals values earlier. If you are interested, here's the matching GUI values for the LineNr and CursorLineNR based on the xterm color chart; However, It sounds like you're pleased with the GUI values that you added:

```
"Lighter Line Number Settings
hi LineNr ctermfg=243 ctermbg=235 guifg=#767676 guibg=#262626

"Winterhold CursorLine Number Color
hi CursorLineNR ctermfg=101 guifg=#87875f
```

![nightvigilgui](https://cloud.githubusercontent.com/assets/11221489/13151971/800c8550-d621-11e5-9d97-813a21bd44a0.jpg)

![nightvigilgui_ethereal](https://cloud.githubusercontent.com/assets/11221489/13151976/83adf46e-d621-11e5-8c67-8578ced36179.jpg)

In regards to other suggestions, yes please open another issue ticket. Let's leave this one open in case others have any input on the subject. 

Thank you btw!

**Comment by ghost** [comment]
Yes! What you pasted in that last comment is perfect for the numbers :-) (IMHO!)
