### ISSUE TITLE
Completion dropdowns

### ISSUE THREAD

**Issue by ghost** [AlessandroYorba/Alduin#8]
Too dark for me :-)

![screenshot_2016-02-18_17-59-26](https://cloud.githubusercontent.com/assets/198665/13152919/6e5f1e2e-d669-11e5-9879-00994ec15773.png)

How about `highlight Pmenu ctermfg=101 ctermbg=233 guifg=#87875f guibg=#121212`?

![screenshot_2016-02-18_18-07-54](https://cloud.githubusercontent.com/assets/198665/13153161/94065600-d66a-11e5-8110-ba1f55e54ea0.png)

**Comment by AlessandroYorba** [comment]
`Pmenu  ctermfg=101 ctermbg=233 guifg=#87875f guibg=#121212`

alduin iterm
![itermpmenu](https://cloud.githubusercontent.com/assets/11221489/13159536/24d5c9be-d647-11e5-921f-9e6a0145051d.png)

alduin Ethereal iterm
![pmenuethereal](https://cloud.githubusercontent.com/assets/11221489/13159543/2ce965b6-d647-11e5-858d-9d6dd606309c.png)

alduin Ethereal GUI
![pmenuetherealgui](https://cloud.githubusercontent.com/assets/11221489/13159557/466f94c4-d647-11e5-90e5-da17f4bab506.png)

**Comment by AlessandroYorba** [comment]
@NightVigil 

`Pmenu ctermfg=101 ctermbg=233 guifg=#87875f guibg=#121212`

will be added to the next commit

**Comment by ghost** [comment]
Cool.

**Comment by AlessandroYorba** [comment]
@NightVigil your Pmenu fix was pushed today. Thanks dude! https://github.com/AlessandroYorba/Alduin/commit/266d799c5c135d0477d3ab21e6aec3584c5badb0
