### ISSUE TITLE
CursorLine too dark

### ISSUE THREAD

**Issue by ghost** [AlessandroYorba/Alduin#9]
This is only a problem with g:alduin_Shout_Become_Ethereal set. I'd suggest `highlight CursorLine ctermbg=235 guibg=#262626`, which looks like it works with Ethereal both set and unset. Respectively:

![screenshot_2016-02-19_11-35-32](https://cloud.githubusercontent.com/assets/198665/13174620/ea15104e-d6fc-11e5-8018-01608cd2be84.png)

![screenshot_2016-02-19_11-36-08](https://cloud.githubusercontent.com/assets/198665/13174630/fb91e5b8-d6fc-11e5-8336-2381f43b52b9.png)

**Comment by AlessandroYorba** [comment]
The default Ethereal CursorLine looks okay to me but I do see your point. Let me play with it some more.

**Comment by ghost** [comment]
To be fair, I'm only using CursorLine with [CtrlP](https://github.com/ctrlpvim/ctrlp.vim), where it's used to select files up and down.
